spring:
  main:
    allow-bean-definition-overriding: true
  webflux:
    base-path: /reactive-flashCard
  data:
    mongodb:
      uri: mongodb://reactive-flashCard:reactive-flashCard@localhost:27017/reactive-flashCard?authSource=admin
